import { ArrowUpRight, Bot, BrainCircuit, Check, ChevronRight, Clock3, ExternalLink, ImageIcon, Menu, MessageSquareText, Network, Sparkles, Star, Zap } from 'lucide-react'

const articles = [
  { category:'Prompt Engineering', title:'【コピペで使える】会議の議事録からタスク・期限を自動抽出するプロンプト', date:'2026.10.03', readTime:'8 min read', excerpt:'議事録から担当者・期限・次のアクションまでを一度に抽出する、現場で使えるプロンプト設計。', accent:'from-blue-500/30 via-cyan-400/10 to-transparent', icon:MessageSquareText, href:'/AI/articles/meeting-minutes-prompt/' },
  { category:'AIツール活用', title:'AI議事録イヤホン「ZENCHORD 1」とは？会議の文字起こし・要約を効率化する使い方', date:'2026.10.03', readTime:'7 min read', excerpt:'会議の記録・文字起こしから、ChatGPTを使った要約・決定事項・ToDo整理まで。AI議事録を仕事で活用する流れを紹介。', accent:'from-emerald-400/25 via-teal-400/10 to-transparent', icon:Network, href:'/AI/articles/zenchord1-ai-minutes/' },
  { category:'AIツール活用', title:'PLAUDとは？会議・商談の録音から文字起こし・要約まで効率化するAIボイスレコーダー', date:'2026.10.03', readTime:'8 min read', excerpt:'録音だけで終わらない。文字起こし・AI要約・情報整理まで、PLAUDを仕事で活用する流れを紹介。', accent:'from-cyan-400/25 via-blue-400/10 to-transparent', icon:Network, href:'/AI/articles/plaud-ai-voice-recorder/' },
  { category:'画像生成・編集AI', title:'Aiarty Image Enhancerとは？ぼやけた画像をAIで高画質化・拡大する方法', date:'2026.10.03', readTime:'7 min read', excerpt:'ブログ・Webサイト・SNSで使う画像をAIで高画質化。ノイズやぼけの補正、画像拡大などの活用方法を紹介。', accent:'from-violet-400/25 via-fuchsia-400/10 to-transparent', icon:ImageIcon, href:'/AI/articles/aiarty-image-enhancer/' },
  { category:'AI活用事例', title:'中小企業が生成AIを導入する最初の一歩', date:'2026.10.03', readTime:'9 min read', excerpt:'いきなり全社導入しない。課題選定から効果測定まで、生成AIを小さく始める5つのステップ。', accent:'from-amber-400/20 via-orange-400/10 to-transparent', icon:BrainCircuit, href:'/AI/articles/small-business-ai-start/' },
]

const tools = [
  { name:'ChatGPT Plus', type:'AIアシスタント', copy:'日々の業務を変える、最初の一歩に。', color:'bg-emerald-400', logo:'✦', href:'#articles' },
  { name:'PLAUD', type:'AIボイスレコーダー', copy:'録音から文字起こし・要約・情報整理まで効率化。', color:'bg-cyan-400', logo:'P', href:'/AI/articles/plaud-ai-voice-recorder/' },
  { name:'ZENCHORD 1', type:'AI議事録イヤホン', copy:'会議の記録から、要約・ToDo整理まで効率化。', color:'bg-orange-400', logo:'Z', href:'/AI/articles/zenchord1-ai-minutes/' },
  { name:'Aiarty Image Enhancer', type:'AI画像高画質化', copy:'ぼやけた画像の補正・高画質化・拡大をAIで。', color:'bg-violet-400', logo:'A', href:'/AI/articles/aiarty-image-enhancer/' },
]

export default function Page(){return <main className="min-h-screen overflow-hidden bg-[#07111f] text-slate-100">
<div className="pointer-events-none fixed inset-0 -z-0 bg-[radial-gradient(circle_at_80%_0%,rgba(30,112,190,0.13),transparent_35%),radial-gradient(circle_at_0%_55%,rgba(15,118,110,0.08),transparent_30%)]"/>
<header className="relative z-10 border-b border-white/[0.08] bg-[#07111f]/80 backdrop-blur-xl"><div className="mx-auto flex max-w-6xl items-center justify-between px-5 py-5 lg:px-8"><a href="#top" className="flex items-center gap-3"><span className="flex size-9 items-center justify-center rounded-xl bg-blue-500"><Bot size={19}/></span><span className="text-lg font-semibold">AI <span className="text-blue-400">WorkLab</span></span></a><nav className="hidden items-center gap-8 text-sm text-slate-400 md:flex"><a href="#top" className="text-white">ホーム</a><a href="#articles" className="hover:text-white">記事一覧</a><a href="#tools" className="hover:text-white">ツール紹介</a><a href="#consulting" className="hover:text-white">運営者 / コンサル</a></nav><a href="/AI/contact/" className="hidden items-center gap-2 rounded-full border border-blue-400/40 bg-blue-400/10 px-4 py-2 text-sm font-medium text-blue-200 sm:flex">お問い合わせ <ArrowUpRight size={15}/></a><button className="rounded-lg p-2 text-slate-300 md:hidden" aria-label="メニュー"><Menu size={22}/></button></div></header>
<section id="top" className="relative z-10 mx-auto max-w-6xl px-5 pb-20 pt-20 lg:px-8 lg:pb-28 lg:pt-28"><div className="grid items-center gap-14 lg:grid-cols-[1.05fr_0.95fr]"><div><div className="mb-7 inline-flex items-center gap-2 rounded-full border border-blue-400/20 bg-blue-400/[0.08] px-3 py-1.5 text-xs font-medium text-blue-300"><Sparkles size={14}/> AI × 実務の知恵を届けるメディア</div><h1 className="max-w-3xl text-5xl font-semibold leading-[1.05] tracking-[-0.045em] text-white sm:text-6xl lg:text-7xl">AIで、日常の業務を<br/><span className="bg-gradient-to-r from-blue-300 via-cyan-300 to-emerald-300 bg-clip-text text-transparent">10倍速くする。</span></h1><p className="mt-7 max-w-xl text-base leading-8 text-slate-400 sm:text-lg">ChatGPT・生成AIを活用した実務プロンプトと、最新AIツールの活用方法を紹介。明日から使える知識を、わかりやすく。</p><div className="mt-9 flex flex-col gap-3 sm:flex-row"><a href="#articles" className="inline-flex items-center justify-center gap-2 rounded-lg bg-blue-500 px-5 py-3.5 text-sm font-semibold text-white">最新記事を読む <ChevronRight size={17}/></a><a href="#consulting" className="inline-flex items-center justify-center gap-2 rounded-lg border border-white/15 bg-white/[0.04] px-5 py-3.5 text-sm font-semibold">法人向けAI導入相談 <ArrowUpRight size={17}/></a></div></div><div className="relative rounded-3xl border border-white/10 bg-[#0d1b2d]/90 p-6"><div className="mb-6 flex items-center justify-between text-xs text-slate-400"><span className="flex items-center gap-2"><span className="size-2 rounded-full bg-emerald-400"/> AI WORKFLOW / 01</span><span>LIVE PREVIEW</span></div><div className="rounded-2xl border border-blue-300/15 bg-gradient-to-br from-blue-500/15 to-transparent p-5"><div className="flex justify-between"><span className="text-sm text-blue-200">今日の生産性</span><Zap className="text-blue-300" size={18}/></div><div className="mt-8 text-5xl font-semibold">+248%</div><div className="mt-7 flex h-20 items-end gap-1.5">{[30,45,38,60,52,72,65,90,77,100,85,100].map((h,i)=><div key={i} className="flex-1 rounded-t-sm bg-gradient-to-t from-blue-500/60 to-cyan-300" style={{height:`${h}%`,opacity:.45+i/22}}/>)}</div></div><div className="mt-4 grid grid-cols-2 gap-3"><div className="rounded-xl border border-white/10 bg-white/[0.03] p-4"><Clock3 size={16} className="mb-3 text-slate-500"/><div className="text-xl font-semibold">6.4h</div><div className="text-xs text-slate-500">saved this week</div></div><div className="rounded-xl border border-white/10 bg-white/[0.03] p-4"><Check size={16} className="mb-3 text-emerald-400"/><div className="text-xl font-semibold">28</div><div className="text-xs text-slate-500">tasks automated</div></div></div></div></div></section>
<section id="articles" className="relative z-10 border-t border-white/[0.07] bg-[#091625]/70 px-5 py-20 lg:px-8 lg:py-24"><div className="mx-auto max-w-6xl"><div className="mb-10"><p className="mb-3 text-xs font-semibold tracking-[0.2em] text-blue-400">FEATURED ARTICLES</p><h2 className="text-3xl font-semibold sm:text-4xl">注目の記事</h2></div><div className="grid gap-5 md:grid-cols-2 lg:grid-cols-3">{articles.map(a=>{const Icon=a.icon;return <a href={a.href} key={a.title} className="group block overflow-hidden rounded-2xl border border-white/10 bg-white/[0.035] transition hover:-translate-y-1 hover:border-blue-300/30"><div className={`relative flex h-40 items-center justify-center bg-gradient-to-br ${a.accent}`}><Icon size={48} strokeWidth={1} className="text-white/80"/></div><div className="p-5"><div className="flex justify-between text-xs"><span className="text-blue-300">{a.category}</span><span className="text-slate-600">{a.date}</span></div><h3 className="mt-4 text-lg font-medium leading-7">{a.title}</h3><p className="mt-3 text-sm leading-6 text-slate-400">{a.excerpt}</p><div className="mt-5 flex items-center gap-1.5 text-xs text-slate-500"><Clock3 size={13}/>{a.readTime}</div></div></a>})}</div></div></section>
<section id="tools" className="relative z-10 mx-auto max-w-6xl px-5 py-20 lg:px-8 lg:py-24"><div className="mb-10"><p className="mb-3 text-xs font-semibold tracking-[0.2em] text-emerald-400">TOOLS WE USE</p><h2 className="text-3xl font-semibold sm:text-4xl">おすすめAIツール</h2><p className="mt-3 text-slate-400">仕事の効率化につながるAIツールを、使い方とあわせて紹介します。</p></div><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{tools.map(t=><a href={t.href} key={t.name} className="group rounded-2xl border border-white/10 bg-white/[0.035] p-5 transition hover:border-emerald-300/30"><div className="flex justify-between"><div className={`flex size-11 items-center justify-center rounded-xl ${t.color} text-lg font-bold text-slate-950`}>{t.logo}</div><ExternalLink size={17} className="text-slate-600"/></div><div className="mt-7 text-xs text-slate-500">{t.type}</div><h3 className="mt-1 font-medium">{t.name}</h3><p className="mt-3 text-sm text-slate-400">{t.copy}</p><div className="mt-5 flex items-center gap-1 text-xs font-medium text-emerald-300">記事を読む <ChevronRight size={14}/></div></a>)}</div></section>
<section id="consulting" className="relative z-10 px-5 pb-20 lg:px-8 lg:pb-28"><div className="mx-auto max-w-6xl rounded-3xl border border-blue-300/20 bg-gradient-to-br from-[#102b4d] via-[#0d2036] to-[#0b1727] p-7 sm:p-10 lg:p-14"><div className="grid gap-12 lg:grid-cols-[1.1fr_0.9fr]"><div><p className="mb-4 text-xs font-semibold tracking-[0.2em] text-blue-300">FOR BUSINESS</p><h2 className="text-3xl font-semibold sm:text-4xl">社内へのChatGPT導入、<br/>最初の一歩を一緒に。</h2><p className="mt-5 max-w-lg leading-7 text-slate-300">ツールを導入するだけではなく、現場に定着する仕組みづくりまで支援します。</p><a href="/AI/contact/" className="mt-8 inline-flex items-center gap-2 rounded-lg bg-white px-5 py-3.5 text-sm font-semibold text-[#0b2038]">導入について相談する <ArrowUpRight size={17}/></a></div><div className="space-y-3">{[['01','プロンプト構築支援'],['02','AIツール選定'],['03','社内レクチャー']].map(([n,t])=><div key={n} className="flex items-center gap-4 rounded-xl border border-white/10 bg-white/[0.05] p-4"><span className="text-sm font-semibold text-blue-300">{n}</span><span className="text-sm font-medium">{t}</span></div>)}</div></div></div></section>
<footer className="relative z-10 border-t border-white/[0.08] px-5 py-8 lg:px-8"><div className="mx-auto flex max-w-6xl flex-col gap-5 text-sm text-slate-500 sm:flex-row sm:items-center sm:justify-between"><div className="flex items-center gap-3"><span className="flex size-7 items-center justify-center rounded-lg bg-blue-500 text-white"><Bot size={15}/></span><span>© 2026 AI WorkLab</span></div><div className="flex gap-6"><a href="/AI/contact/" className="hover:text-white">お問い合わせ</a><a href="/AI/privacy/" className="hover:text-white">プライバシーポリシー</a></div></div></footer>
</main>}
